name: "NSPanel Manager"
description: "Container for Sonoff NSPanel management with a simple and intuitive UI"
version: 0.1.31-public_beta_beta1b2
image: docker.io/nspanelmanager/nspanelmanager-{arch}
slug: "nspanelmanager"
url: "https://nspanelmanager.com"
webui: http://[HOST]:[PORT:8000]/
panel_icon: mdi:fit-to-screen
ports:
  8000/tcp: 8000
environment:
  IS_HOME_ASSISTANT_ADDON: "true"
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
