name: "NSPanel Manager"
description: "NSPanel Manager container for Sonoff NSPanel management with a simple and intuitive UI."
version: "0.0.6"
slug: "nspanelmanager"
url: "https://nspanelmanager.com"
webui: http://[HOST]:[PORT:8000]/
panel_icon: mdi:fit-to-screen
ports:
  8000/tcp: 8000
  8001/tcp: 8001
environment:
  IS_HOME_ASSISTANT_ADDON: "true"
map:
  - config:rw
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
