name: "Publish"

on:
  release:
    types: [published]

jobs:
  copy_config_template:
    name: Update Home Assistant add-on version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: read
    steps:
      - uses: actions/checkout@v2
      - name: Update Home Assistant config.yaml version
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "[0-9]+.[0-9]+.[0-9]+"
          replace: "${{ github.ref_name }}"
          regex: true
          include: "docker/config.yaml"
      - name: Push changes to repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target docker \
            --image NSPanelManager-{arch} \
            --version ${{ github.ref_name }} \
            --release ${{ github.ref_name }} \
            --docker-hub ${{ secrets.DOCKERHUB_USERNAME }}
