name: "Publish"

on:
  release:
    types: [published]
    branches:
      - 'main'
      - 'beta'

jobs:
  publish:
    if: ${{ !github.event.act }} # skip during local actions testing
    name: Publish
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - run: |
          sed -i "s/^version: [0-9\.]\+/version: ${{ github.ref_name }}/g" docker/config.yaml
          sed -i "s/[0-9]\+\.[0-9]\+\.[0-9]\+/${{ github.ref_name }}/g" docker/web/nspanelmanager/web/templates/footer.html
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ !github.event.act }} # skip during local actions testing
        with:
          commit_message: Push updated version back to repo
      - name: Get image name
        shell: bash
        id: image_name
        run: |
          if [ "${{ github.event.release.prerelease }}" != "true" ]; then
            echo "Image name: NSPanelManager"
            echo "name=NSPanelManager" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.release.prerelease }}" == "true" ]; then
            echo "Image name: NSPanelManager-beta"
            echo "name=NSPanelManager-beta" >> $GITHUB_OUTPUT
          else
            echo "Cannot determine image name!"
            exit 1
          fi
      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Publish
      #   uses: home-assistant/builder@master
      #   with:
      #     args: |
      #       --all \
      #       --target docker \
      #       --image NSPanelManager-{arch} \
      #       --version ${{ github.ref_name }} \
      #       --release ${{ github.ref_name }} \
      #       --docker-hub ${{ secrets.DOCKERHUB_USERNAME }}
